# Use an official Node.js image as the base image
FROM node:21-alpine AS build

# Set the working directory to /app
WORKDIR /app

# Copy the package.json file
COPY package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Build the application
RUN npm run build

# Create a new stage for Nginx
FROM nginx:alpine

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built frontend code from the previous stage
COPY --from=build /app/dist usr/share/nginx/html

# Expose the port
EXPOSE 80

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]