version: '3'

networks:
  app-net:
    driver: bridge

services:
  qa_db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: context_qa_db
    ports:
      - 5432:5432
    restart: always
    networks:
      - app-net

  ollama_service:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    restart: always
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:psql@qa_db:5432/context_qa_db
      - OLLAMA_SERVICE_URL=http://ollama_service:11434
      # - OPENAI_API_KEY=
    depends_on:
      - ollama_service
      - qa_db
    networks:
      - app-net
