version: '3'
services:
  qa_db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always
    networks:
      - app-net

  ollama_service:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    restart: always
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@qa_db:5432/${POSTGRES_DB}
      - OLLAMA_SERVICE_URL=http://ollama_service:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - ollama_service
      - qa_db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge